import type { Palette, Tokens } from './schema.ts';

export const GENERATED_HEADER = 'GENERATED by packages/design-tokens (pnpm tokens). Do not edit.';

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const rem = (px: number) => `${px / 16}rem`;

function colorVars(palette: Palette, priceSource: Record<string, string>, indent: string): string[] {
  return [
    ...Object.entries(palette).map(([k, v]) => `${indent}--mn-color-${kebab(k)}: ${v.toLowerCase()};`),
    ...Object.entries(priceSource).map(([k, v]) => `${indent}--mn-price-${kebab(k)}: ${v.toLowerCase()};`),
  ];
}

/** CSS custom properties; dark mode follows the system unless `data-theme` forces one. */
export function toCss(t: Tokens): string {
  const fonts = Object.entries(t.typography).flatMap(([name, s]) => [
    `  --mn-font-${kebab(name)}-size: ${rem(s.size)};`,
    `  --mn-font-${kebab(name)}-line-height: ${rem(s.lineHeight)};`,
    `  --mn-font-${kebab(name)}-weight: ${s.weight};`,
  ]);
  const lines = [
    `/* ${GENERATED_HEADER} */`,
    ':root {',
    '  color-scheme: light dark;',
    ...colorVars(t.color.light, t.priceSource.light, '  '),
    ...fonts,
    ...Object.entries(t.spacing).map(([k, v]) => `  --mn-space-${kebab(k)}: ${v}px;`),
    ...Object.entries(t.radius).map(([k, v]) => `  --mn-radius-${kebab(k)}: ${v}px;`),
    `  --mn-touch-target-min: ${t.touchTarget.min}px;`,
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    "  :root:not([data-theme='light']) {",
    ...colorVars(t.color.dark, t.priceSource.dark, '    '),
    '  }',
    '}',
    '',
    "[data-theme='light'] {",
    '  color-scheme: light;',
    '}',
    '',
    ":root[data-theme='dark'] {",
    '  color-scheme: dark;',
    ...colorVars(t.color.dark, t.priceSource.dark, '  '),
    '}',
  ];
  return `${lines.join('\n')}\n`;
}
