// GENERATED by packages/design-tokens (pnpm tokens). Do not edit.
package com.maubautista.maunedas.core.designsystem

/** Design tokens from packages/design-tokens/tokens.json. Colors are ARGB. */
object Tokens {
    object ColorLight {
        const val primary: Long = 0xFF1B6B3A
        const val onPrimary: Long = 0xFFFFFFFF
        const val surface: Long = 0xFFFFFFFF
        const val onSurface: Long = 0xFF1A1C1A
        const val surfaceVariant: Long = 0xFFEEF2EC
        const val onSurfaceVariant: Long = 0xFF42493F
        const val outline: Long = 0xFF737970
        const val error: Long = 0xFFB3261E
        const val onError: Long = 0xFFFFFFFF
        const val warning: Long = 0xFF8A5300
        const val onWarning: Long = 0xFFFFFFFF
        const val success: Long = 0xFF1B6B3A
        const val onSuccess: Long = 0xFFFFFFFF
    }

    object ColorDark {
        const val primary: Long = 0xFF7DD99A
        const val onPrimary: Long = 0xFF00391A
        const val surface: Long = 0xFF111411
        const val onSurface: Long = 0xFFE1E3DE
        const val surfaceVariant: Long = 0xFF1D211D
        const val onSurfaceVariant: Long = 0xFFC2C9BD
        const val outline: Long = 0xFF8C9388
        const val error: Long = 0xFFFFB4AB
        const val onError: Long = 0xFF690005
        const val warning: Long = 0xFFFFB95C
        const val onWarning: Long = 0xFF4A2800
        const val success: Long = 0xFF7DD99A
        const val onSuccess: Long = 0xFF00391A
    }

    object PriceSourceLight {
        const val purchase: Long = 0xFF00796B
        const val shelf: Long = 0xFFB26A00
        const val web: Long = 0xFF1565C0
    }

    object PriceSourceDark {
        const val purchase: Long = 0xFF4DB6AC
        const val shelf: Long = 0xFFFFB74D
        const val web: Long = 0xFF64B5F6
    }

    object Typography {
        object Display {
            const val sizeSp: Int = 32
            const val lineHeightSp: Int = 40
            const val weight: Int = 600
        }
        object Title {
            const val sizeSp: Int = 22
            const val lineHeightSp: Int = 28
            const val weight: Int = 600
        }
        object Body {
            const val sizeSp: Int = 16
            const val lineHeightSp: Int = 24
            const val weight: Int = 400
        }
        object Label {
            const val sizeSp: Int = 14
            const val lineHeightSp: Int = 20
            const val weight: Int = 500
        }
        object Caption {
            const val sizeSp: Int = 12
            const val lineHeightSp: Int = 16
            const val weight: Int = 400
        }
    }

    /** Values in dp. */
    object Spacing {
        const val xs: Int = 4
        const val sm: Int = 8
        const val md: Int = 12
        const val lg: Int = 16
        const val xl: Int = 24
        const val xxl: Int = 32
    }

    /** Values in dp. */
    object Radius {
        const val sm: Int = 4
        const val md: Int = 8
        const val lg: Int = 12
        const val xl: Int = 16
        const val full: Int = 999
    }

    const val touchTargetMinDp: Int = 48
}
